<!--add header -->
<?php include_once __DIR__ . '/../header.php'; ?>

<!-- Left side column. contains the logo and sidebar -->
<?php include_once 'main_sidebar.php'; ?> <!-- main sidebar area -->
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header" >
        <h1>
            <?= $Title ?>
            <small> <?= $Title ?></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="<?= $base_url ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active"><?php echo $Title ?></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content" style="min-height: 1050px;" >
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-header">
                        <?php
//                if (!$date_filter) {
//                    $attributes = array(
//                        'clase' => 'form-inline',
//                        'method' => 'post');
//                    echo form_open('', $attributes)
                        ?>
                        <form action="<?= site_url('/due/customer_payment') ?>" method="get">
                            <div class="form-group col-md-5">
                                <label>Customer Name or Code</label>
                                <div class="input-group">
                                   <?=$customers_dropdown;?>
                                </div>

                            </div>
                            <div class="form-group col-md-5">
                                <label>Date Range:</label>
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" name="date_range" value="<?= isset($date_range) ? $date_range : ''; ?>" class="form-control pull-right" id="reservation"  title="This is not a date"/>
                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                            <div class="form-group col-md-2" style="margin-top: 25px;">
                                <button type="submit" name="btn_submit" value="true" class="btn btn-primary"><i class="fa fa-search"></i></button>
                                <?= anchor(current_url() . '/due/customer_due', '<i class="fa fa-refresh"></i>', ' class="btn btn-success"') ?>
                            </div>
                        </form>
                    </div>

                </div>
            </div>

            <div class="col-md-12" id="block">

                <div class="box">
                    <?php
                    if (!isset($customer_due_payment)) {
                        ?>
                        <div class="box-header">
                            <h3 class="box-title">Customer Due Current View</h3>
                        </div><!-- /.box-header -->

                        <div class="box-body">
                            <?php
                            echo $glosary->output;
                            ?>
                        </div><!-- /.box-body -->
                        <?php
                    }if (isset($customer_due_payment)) {
                        ?>
                        <div class="box-header">
                            <h3 class="text-center"><?= $this->config->item('SITE')['name'] ?></h3>
                            <p class="text-center"> <?= $Title ?> Report</p>
                            <div style="margin-bottom: 60px;">
                                <p class="pull-left" style="margin-left:5px">Report Generated by: <?php echo $_SESSION['username'] ?></p>
                                <input style="margin-bottom: 10px;" class="only_print pull-right btn btn-primary" type="button" id="print"  onClick="printDiv('block')"  value="Print Report"/>
                            </div>
                            <div style="color: #777777;">
                                <p class="pull-left" style="margin-left:5px"> <strong>Customer Id: </strong> <?php echo $customer_id; ?></p>
                                <div class="pull-right">Report Date: <?php echo date('d-M-Y H:i:s', now()); ?></div>
                            </div>
                        </div>
                        <div class="box-body">
                            <table  class ="table table-bordered table-striped" border="0" cellpadding="4" cellspacing="0" style="background: #fff;">
                                <thead>
                                    <tr style="background:#ddd">
                                        <th>Customer Name</th>
                                        <th>Amount (TK)</th>
                                        <th>Memo ID</th>
                                        <th>Payment Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $total_payment = 0;
                                    foreach ($customer_due_payment as $due_payment) {
                                        $total_payment += $due_payment->paid_amount;
                                        ?>
                                        <tr>
                                            <td><?php echo $due_payment->name; ?></td>
                                            <td class="text-right faka_formate"><?php echo $due_payment->paid_amount; ?></td>
                                            <td><?php echo $due_payment->id_total_sales; ?></td>
                                            <td><?php echo date('d/m/Y', strtotime($due_payment->payment_date)); ?></td>
                                        </tr>


                                        <?php
                                    }
                                    ?>
                                    <tr>
                                        <td>Total: </td>
                                        <td class="text-right faka_formate"><?php echo $total_payment; ?></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>
                        <?php
                    }
                    ?>

                </div>

            </div>
        </div>




    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- insert book -->
<?php include_once __DIR__ . '/../footer.php'; ?>
<script>jQuery('.add_payment').html("Add Payment");</script>