<!--add header -->
<?php include_once __DIR__ . '/../header.php'; ?>

<!-- Left side column. contains the logo and sidebar -->
<?php include_once 'main_sidebar.php'; ?> <!-- main sidebar area -->
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <?= $Title ?>
            <small> <?= $Title ?></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="<?= $base_url ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active"><?php echo $Title ?></li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12" id="block">

                <div id="employee_table" style="margin-top: 50px;">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="text-center"><?= $this->config->item('SITE')['name'] ?></h3>
                            <p class="text-center"> <?= $Title ?> Report</p>
                            <div style="margin-bottom: 60px;">
                                <p class="pull-left" style="margin-left:5px">Report Generated by: <?php echo $_SESSION['username'] ?></p>
                                <input style="margin-bottom: 10px;" class="only_print pull-right btn btn-primary" type="button" id="print"  onClick="printDiv('block')"  value="Print Report"/>
                            </div>
                            <div style="color: #777777;">
                                <p class="pull-left" style="margin-left:5px"> <strong>Month : </strong> <?php echo date('F', now()); ?></p>
                                <div class="pull-right">Report Date: <?php echo date('Y-m-d H:i:s', now()); ?></div>
                            </div>
                        </div>
                        <div class="box-body">
                            <table  class ="table table-bordered table-striped" border="0" cellpadding="4" cellspacing="0" style="background: #fff;">
                                <thead>
                                    <tr style="background:#ddd">
                                        <th>Employee Name</th>
                                        <th>Date of Issue</th>
                                        <th>Amount of Salary</th>
                                        <th>Amount of bonus</th>
                                        <th>Loan</th>
                                        <th>Loan Installment</th>
                                        <th>Advance</th>
                                        <th>Net Salary</th>
                                        <th>Paid or Not</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    foreach ($all_salary_info as $value) {
//                                        print_r($value);
                                        $salary = $value->amount_salary_payment;
                                        $bonus = $value->amount_salary_bonus;
                                        $total = $salary + $bonus;
                                        $loan_installment = $value->installments_loan;
                                        $advance = $value->amount_given_salary_advance;
                                        $deduction = $loan_installment + $advance;
                                        $total = $total - $deduction;
                                        ?>
                                        <tr>
                                            <td><?php echo $value->name_employee; ?></td>
                                            <td><?php echo date('d/m/Y', strtotime($value->issue_salary_payment)); ?></td>
                                            <td><?php echo $value->amount_salary_payment; ?></td>
                                            <td><?php echo $value->amount_salary_bonus; ?></td>
                                            <td><?php echo $value->amount_loan; ?></td>
                                            <td><?php echo $value->installments_loan; ?></td>
                                            <td><?php echo $value->amount_given_salary_advance; ?></td>
                                            <td><?php echo $total; ?></td>
                                            <td>
                                                <?php
                                                if ($value->status_salary_payment == 2) {
                                                    ?>
                                                    <label for="">
                                                        PAID
                                                    </label>
                                                    <?php
                                                }
                                                ?>
                                            </td>

                                        </tr>
                                        <?php
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
</div>
</section><!-- /.content -->
</div><!-- /.content-wrapper -->

<!-- insert book -->



<?php include_once __DIR__ . '/../footer.php'; ?>
